# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.2.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: jayden@jaydendang.com
author_name: jayden-dang
contract_name: auction
deployment_language: python
preset_name: production
project_name: auction-contracts

