# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: jayden@jaydendang.com
author_name: jayden-dang
cloud_provider: vercel
contract_name: auction
deployment_language: python
preset_name: production
project_name: auction

