# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.7
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: jayden@jaydendang.com
author_name: jayden-dang
cloud_provider: vercel
preset_name: production
project_name: auction-frontend

